server:
    port: 8080
thingspeak:
    key:
    channel: field1
---

spring:
    profiles: openshift
logging:
    file: ${OPENSHIFT_LOG_DIR}/app.log

server:
    port: ${OPENSHIFT_DIY_PORT}
    address: ${OPENSHIFT_DIY_IP}


